services:
  kafka-hw03:
    image: confluentinc/cp-kafka:8.0.0
    env_file:
      - ./.env
    container_name: kafka-hw03
    hostname: kafka-hw03
    restart: unless-stopped
    networks:
      - kafka-network
    ports:
      - "19092:39092"
    environment:
        KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: false
        KAFKA_AUTHORIZER_CLASS_NAME: 'org.apache.kafka.metadata.authorizer.StandardAuthorizer'
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-hw03:9093'
        KAFKA_INTER_BROKER_LISTENER_NAME: 'INSIDE'
        KAFKA_LISTENERS: 'INSIDE://:9092,CONTROLLER://:9093,OUTSIDE://:19092'
        KAFKA_ADVERTISED_LISTENERS: 'INSIDE://kafka-hw03:9092,OUTSIDE://localhost:19092'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INSIDE:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT,OUTSIDE:SASL_PLAINTEXT'
        KAFKA_NODE_ID: 1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/secrets/kafka-server-jaas.conf'
        KAFKA_PROCESS_ROLES: 'broker,controller'
        KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
        KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
        KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
        KAFKA_SUPER_USERS: 'User:admin'
    volumes:
      - kafka-hw03-data:/var/lib/kafka/data
      - ./secrets:/etc/kafka/secrets

volumes:
  kafka-hw03-data:

networks:
  kafka-network:
    driver: bridge